apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-something
  name: frontend-something
  namespace: otabek
spec:

  replicas: 1
  selector:
    matchLabels:
      app: frontend-something
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-something
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: otabek
                    operator: In
                    values:
                      - tursunboev

      containers:
      - image: nvrbckdown/something
        name: something
        livenessProbe:
          tcpSocket:
            port: 80
        resources: {}
status: {}
