apiVersion: v1
kind: Pod
metadata:
  labels:
    author: otabek
    last: final
  name: nginx2
  namespace: otabek
spec:
  containers:
  - image: nginx
    name: nginx2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
