apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: node-printer
  namespace: otabek
spec:

  jobTemplate:
    metadata:
      creationTimestamp: null
      name: node-printer
    spec:
      completions: 10
      parallelism: 5
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx
            name: node-printer
            resources: {}
            command: [ "/bin/sh" ]
            args: [ "-c", "echo Running on node: $NODE_NAME" ]
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
          restartPolicy: OnFailure

  schedule: '*/2 * * * *'
status: {}
